---
- name: Create gtk conf dir
  file:
    path: ~/.config/gtk-3.0/
    state: directory

- name: Configure GTK3
  copy:
    src: settings.ini
    dest: ~/.config/gtk-3.0/

- name: Configure GTK2
  template:
    src: gtkrc-2.0.j2
    dest: ~/.gtkrc-2.0

- name: Configure Qt as GTK theme
  copy:
    src: Trolltech.conf
    dest: ~/.config/

- name: Link Xdefaults
  file:
    src: ~/.Xresources
    dest: ~/.Xdefaults
    state: link
    force: yes

- name: Create .Xresources.d dir
  file:
    path: ~/.Xresources.d
    state: directory

- name: Configure Cursors
  copy:
    src: cursor
    dest: ~/.Xresources.d/

- name: Init Cursors in .Xresources
  lineinfile:
    path: ~/.Xresources
    create: yes
    state: present
    line: '#include ".Xresources.d/cursor"'
