---
- name: Configure ssh-agent
  copy:
    src: ssh-agent.service
    dest: ~/.config/systemd/user/
  notify: enable ssh-agent

- name: Configure pam environment
  copy:
    src: pam_environment
    dest: ~/.pam_environment
